In [58]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [31]:
df=pd.read_csv('car_price_prediction.csv')

In [32]:
df1=int(df['Mileage'][0].strip(' km'))

In [33]:
df1

186005

In [34]:
a=0
for i in df['Mileage']:
    df['Mileage'][a]=int(i.strip(' km'))
    a=a+1

In [35]:
df['Mileage']

0        186005
1        192000
2        200000
3        168966
4         91901
          ...
19232    300000
19233    161600
19234    116365
19235     51258
19236    186923
Name: Mileage, Length: 19237, dtype: object

In [36]:
type(df['Mileage'][0])

int

In [37]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923,4.0,Automatic,Front,04-May,Left wheel,White,12

In [38]:
a=0
b=0
for i in df['Levy']:
    if i == '-':
        df['Levy'][a]=0
    else:
        df['Levy'][a]=int(i)
    a=a+1

In [39]:
mean = df['Levy'].mean()
for i in df['Levy']:
    if i == 0:
        df['Levy'][b]=mean
    b=b+1

In [40]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,632.528669,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,632.528669,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923,4.0,Automatic,Front,04-May,Left wheel,White,12

In [41]:
for index,item in enumerate(df.Manufacturer.unique()):
    for index2,i in enumerate(df['Manufacturer']):
        if i == item:
            df['Manufacturer'][index2]=index

In [42]:
for index,item in enumerate(df.Model.unique()):
    for index2,i in enumerate(df['Model']):
        if i == item:
            df['Model'][index2]=index

In [43]:
for index,item in enumerate(df.Category.unique()):
    for index2,i in enumerate(df['Category']):
        if i == item:
            df['Category'][index2]=index

In [44]:
for index,i in enumerate(df['Leather interior']):
    if i == 'Yes':
        df['Leather interior'][index] = 1
    elif i == 'No':
        df['Leather interior'][index] = 0

In [45]:
df['Leather interior'][0]

1

In [46]:
for index,item in enumerate(df['Fuel type'].unique()):
    for index2,i in enumerate(df['Fuel type']):
        if i == item:
            df['Fuel type'][index2]=index

In [47]:
df['Fuel type']

0        0
1        1
2        1
3        0
4        1
        ..
19232    3
19233    1
19234    2
19235    2
19236    0
Name: Fuel type, Length: 19237, dtype: object

In [48]:
for index,i in enumerate(df['Fuel type'].unique()):
    for index2,i in enumerate(df['Fuel type']):
        if i == item:
            df['Fuel type'][index2]=index

In [49]:
def my_func(name):
    for index,item in enumerate(df[name].unique()):
        for index2,i in enumerate(df[name]):
            if i == item:
                df[name][index2]=index

In [50]:
my_func('Engine volume')

In [51]:
df['Engine volume']

0         0
1         1
2         2
3         3
4         2
         ..
19232    10
19233     6
19234     4
19235     4
19236     6
Name: Engine volume, Length: 19237, dtype: object

In [52]:
my_func('Gear box type')

In [53]:
my_func('Drive wheels')

In [54]:
my_func('Doors')

In [55]:
my_func('Wheel')

In [56]:
my_func('Color')

In [60]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,0,0,2010,0,1,0,0,186005,6.0,0,0,0,0,0,12
1,44731507,16621,1018,1,1,2011,0,0,1,1,192000,6.0,1,0,0,0,1,8
2,45774419,8467,632.528669,2,2,2006,1,0,1,2,200000,4.0,2,1,0,1,1,2
3,45769185,3607,862,3,3,2011,0,1,0,3,168966,4.0,0,0,0,0,2,0
4,45809263,11726,446,2,2,2014,1,1,1,2,91901,4.0,0,1,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,632.528669,6,383,1999,6,1,3,10,300000,4.0,3,2,1,0,0,5
19233,45778856,15681,831,4,6,2011,2,1,1,6,161600,4.0,1,1,0,0,6,8
19234,45804997,26108,836,4,42,2010,0,1,2,4,116365,4.0,0,1,0,0,3,4
19235,45793526,5331,1288,1,44,2007,0,1,2,4,51258,4.0,0,1,0,0,1,4
19236,45813273,470,753,4,6,2012,2,1,0,6,186923,4.0,0,1,0,0,2,12

In [67]:
features =['Levy','Manufacturer','Model','Prod. year','Category','Leather interior','Fuel type','Engine volume','Mileage','Cylinders','Gear box type','Drive wheels','Doors','Wheel','Color','Airbags']
label=['Price']
X = df[features].values
y= df[label].values

In [68]:
X

array([[1399, 0, 0, ..., 0, 0, 12],
       [1018, 1, 1, ..., 0, 1, 8],
       [632.5286687113376, 2, 2, ..., 1, 1, 2],
       ...,
       [836, 4, 42, ..., 0, 3, 4],
       [1288, 1, 44, ..., 0, 1, 4],
       [753, 4, 6, ..., 0, 2, 12]], dtype=object)

In [69]:
y

array([[13328],
       [16621],
       [ 8467],
       ...,
       [26108],
       [ 5331],
       [  470]], dtype=int64)

In [71]:
from sklearn.model_selection import train_test_split



# 60% Train, 20% Validation, %20 Test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42) 

X_valid, X_test, y_valid, y_test = train_test_split(X_test, y_test, test_size=0.5, random_state=42)



print(f'Total # of sample in whole dataset: {len(X)}')

print(f'Total # of sample in train dataset: {len(X_train)}')

print(f'Total # of sample in validation dataset: {len(X_valid)}')

print(f'Total # of sample in test dataset: {len(X_test)}')

Total # of sample in whole dataset: 19237
Total # of sample in train dataset: 11542
Total # of sample in validation dataset: 3847
Total # of sample in test dataset: 3848

In [73]:
from sklearn.linear_model import LinearRegression



# Create linear regression object

reg = LinearRegression()



# Train the model using the training sets

reg.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error



predictions = reg.predict(X_valid)

print(f'MAE Score: {mean_absolute_error(predictions, y_valid)}')

MAE Score: 13486.167348991165

In [74]:
reg = LinearRegression(normalize=True)

reg.fit(X_train, y_train)



predictions = reg.predict(X_valid)

print(f'MAE Score: {mean_absolute_error(predictions, y_valid)}')

MAE Score: 13486.167349003368

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(

In [85]:
from sklearn.linear_model import PoissonRegressor 
poi_reg = PoissonRegressor(max_iter=3847)

poi_reg.fit(X_train, y_train.ravel())



predictions = poi_reg.predict(X_valid)

print(f'MAE Score: {mean_absolute_error(predictions, y_valid)}')

MAE Score: 12772.152630347853

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)

In [79]:
poi_reg = PoissonRegressor(max_iter=10000)

poi_reg.fit(X_train, y_train.ravel())



predictions = poi_reg.predict(X_valid)

print(f'MAE Score: {mean_absolute_error(predictions, y_valid)}')

MAE Score: 12772.152630347853

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)

In [80]:
poi_reg = PoissonRegressor(tol=1e-2, max_iter=10000)

poi_reg.fit(X_train, y_train.ravel())



predictions = poi_reg.predict(X_valid)

print(f'MAE Score: {mean_absolute_error(predictions, y_valid)}')

MAE Score: 12772.152630347853

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)

In [81]:
#Trying cross validation



from sklearn.model_selection import cross_validate

from sklearn.metrics import make_scorer, mean_absolute_error, mean_squared_error



scoring = {'mae': make_scorer(mean_absolute_error)}



model = LinearRegression()

scores = cross_validate(model, X_train, y_train, cv=10, scoring=scoring)



print(f"Average cross validation MAE score: {scores['test_mae'].mean()}")

Average cross validation MAE score: 16087.444258510903

In [82]:
model = LinearRegression(normalize=True)

scores = cross_validate(model, X_train, y_train, cv=10, scoring=scoring)



print(f"Average cross validation MAE score: {scores['test_mae'].mean()}")

Average cross validation MAE score: 16087.444258521946

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(

In [83]:
model = PoissonRegressor(max_iter=1000)

scores = cross_validate(model, X_train, y_train.ravel(), cv=10, scoring=scoring)



print(f"Average cross validation MAE score: {scores['test_mae'].mean()}")

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)

Average cross validation MAE score: 15280.02597882165

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)

In [86]:
#Now with the model we get the least mae we use that model to apply predictions on our test set

from sklearn.metrics import mean_absolute_error



model = PoissonRegressor(max_iter=3847)

model.fit(X_train, y_train)



predictions = model.predict(X_test)

print(f'Test (Final) MAE Score: {mean_absolute_error(predictions, y_test)}')

Test (Final) MAE Score: 12958.609048630493

C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:132: RuntimeWarning: divide by zero encountered in true_divide
  return -2 * (y - y_pred) / self.unit_variance(y_pred)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\linear_model\_glm\glm.py:42: RuntimeWarning: invalid value encountered in multiply
  temp = d1 * family.deviance_derivative(y, y_pred, weights)
C:\Users\alphant.INGAGE\Anaconda3\lib\site-packages\sklearn\_loss\glm_distribution.py:323: RuntimeWarning: divide by zero encountered in true_divide
  dev = 2 * (xlogy(y, y / y_pred) - y + y_pred)

In [87]:
predictions

array([19370.42384335, 19370.42384335, 19370.42384335, ...,
       19370.42384335, 19370.42384335, 19370.42384335])